# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cipango-jars}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dominique Broeglin"]
  s.date = %q{2010-09-08}
  s.description = %q{Cipango and Jetty minimal dependencies}
  s.email = %q{dominique.broeglin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cipango-jars.gemspec",
     "lib/cipango-1.0.jar",
     "lib/cipango-jars.rb",
     "lib/jetty-6.1.24.jar",
     "lib/jetty-util-6.1.24.jar",
     "lib/servlet-api-2.5-20081211.jar",
     "lib/sip-api-1.1.jar",
     "test/helper.rb",
     "test/test_cipango-jars.rb"
  ]
  s.homepage = %q{http://github.com/dbroeglin/cipango-jars}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Cipango and Jetty minimal dependencies}
  s.test_files = [
    "test/helper.rb",
     "test/test_cipango-jars.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

